/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LivestockRouteImport } from './routes/livestock'
import { Route as FarmLandRouteImport } from './routes/farm-land'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsCodeRouteImport } from './routes/products.$code'
import { Route as LivestockCodeRouteImport } from './routes/livestock.$code'
import { Route as FarmLandCodeRouteImport } from './routes/farm-land.$code'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestockRoute = LivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmLandRoute = FarmLandRouteImport.update({
  id: '/farm-land',
  path: '/farm-land',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCodeRoute = ProductsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ProductsRoute,
} as any)
const LivestockCodeRoute = LivestockCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => LivestockRoute,
} as any)
const FarmLandCodeRoute = FarmLandCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => FarmLandRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/farm-land': typeof FarmLandRouteWithChildren
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/farm-land/$code': typeof FarmLandCodeRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/farm-land': typeof FarmLandRouteWithChildren
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/farm-land/$code': typeof FarmLandCodeRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/farm-land': typeof FarmLandRouteWithChildren
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/farm-land/$code': typeof FarmLandCodeRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/farm-land'
    | '/livestock'
    | '/products'
    | '/admin'
    | '/farm-land/$code'
    | '/livestock/$code'
    | '/products/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/farm-land'
    | '/livestock'
    | '/products'
    | '/admin'
    | '/farm-land/$code'
    | '/livestock/$code'
    | '/products/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/farm-land'
    | '/livestock'
    | '/products'
    | '/_authenticated/admin'
    | '/farm-land/$code'
    | '/livestock/$code'
    | '/products/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FarmLandRoute: typeof FarmLandRouteWithChildren
  LivestockRoute: typeof LivestockRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestock': {
      id: '/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof LivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-land': {
      id: '/farm-land'
      path: '/farm-land'
      fullPath: '/farm-land'
      preLoaderRoute: typeof FarmLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$code': {
      id: '/products/$code'
      path: '/$code'
      fullPath: '/products/$code'
      preLoaderRoute: typeof ProductsCodeRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/livestock/$code': {
      id: '/livestock/$code'
      path: '/$code'
      fullPath: '/livestock/$code'
      preLoaderRoute: typeof LivestockCodeRouteImport
      parentRoute: typeof LivestockRoute
    }
    '/farm-land/$code': {
      id: '/farm-land/$code'
      path: '/$code'
      fullPath: '/farm-land/$code'
      preLoaderRoute: typeof FarmLandCodeRouteImport
      parentRoute: typeof FarmLandRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FarmLandRouteChildren {
  FarmLandCodeRoute: typeof FarmLandCodeRoute
}

const FarmLandRouteChildren: FarmLandRouteChildren = {
  FarmLandCodeRoute: FarmLandCodeRoute,
}

const FarmLandRouteWithChildren = FarmLandRoute._addFileChildren(
  FarmLandRouteChildren,
)

interface LivestockRouteChildren {
  LivestockCodeRoute: typeof LivestockCodeRoute
}

const LivestockRouteChildren: LivestockRouteChildren = {
  LivestockCodeRoute: LivestockCodeRoute,
}

const LivestockRouteWithChildren = LivestockRoute._addFileChildren(
  LivestockRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCodeRoute: typeof ProductsCodeRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCodeRoute: ProductsCodeRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FarmLandRoute: FarmLandRouteWithChildren,
  LivestockRoute: LivestockRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
