/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LivestockRouteImport } from './routes/livestock'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealEstateCodeRouteImport } from './routes/real-estate.$code'
import { Route as ProductsCodeRouteImport } from './routes/products.$code'
import { Route as LivestockCodeRouteImport } from './routes/livestock.$code'
import { Route as BlogGuideToBuyingAgriculturalLandTamilNaduRouteImport } from './routes/blog.guide-to-buying-agricultural-land-tamil-nadu'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LivestockRoute = LivestockRouteImport.update({
  id: '/livestock',
  path: '/livestock',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateCodeRoute = RealEstateCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RealEstateRoute,
} as any)
const ProductsCodeRoute = ProductsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ProductsRoute,
} as any)
const LivestockCodeRoute = LivestockCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => LivestockRoute,
} as any)
const BlogGuideToBuyingAgriculturalLandTamilNaduRoute =
  BlogGuideToBuyingAgriculturalLandTamilNaduRouteImport.update({
    id: '/blog/guide-to-buying-agricultural-land-tamil-nadu',
    path: '/blog/guide-to-buying-agricultural-land-tamil-nadu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/real-estate': typeof RealEstateRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/guide-to-buying-agricultural-land-tamil-nadu': typeof BlogGuideToBuyingAgriculturalLandTamilNaduRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
  '/real-estate/$code': typeof RealEstateCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/real-estate': typeof RealEstateRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/guide-to-buying-agricultural-land-tamil-nadu': typeof BlogGuideToBuyingAgriculturalLandTamilNaduRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
  '/real-estate/$code': typeof RealEstateCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/livestock': typeof LivestockRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/real-estate': typeof RealEstateRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/guide-to-buying-agricultural-land-tamil-nadu': typeof BlogGuideToBuyingAgriculturalLandTamilNaduRoute
  '/livestock/$code': typeof LivestockCodeRoute
  '/products/$code': typeof ProductsCodeRoute
  '/real-estate/$code': typeof RealEstateCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/livestock'
    | '/products'
    | '/real-estate'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/guide-to-buying-agricultural-land-tamil-nadu'
    | '/livestock/$code'
    | '/products/$code'
    | '/real-estate/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/livestock'
    | '/products'
    | '/real-estate'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/guide-to-buying-agricultural-land-tamil-nadu'
    | '/livestock/$code'
    | '/products/$code'
    | '/real-estate/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/livestock'
    | '/products'
    | '/real-estate'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/blog/guide-to-buying-agricultural-land-tamil-nadu'
    | '/livestock/$code'
    | '/products/$code'
    | '/real-estate/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LivestockRoute: typeof LivestockRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  RealEstateRoute: typeof RealEstateRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogGuideToBuyingAgriculturalLandTamilNaduRoute: typeof BlogGuideToBuyingAgriculturalLandTamilNaduRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livestock': {
      id: '/livestock'
      path: '/livestock'
      fullPath: '/livestock'
      preLoaderRoute: typeof LivestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate/$code': {
      id: '/real-estate/$code'
      path: '/$code'
      fullPath: '/real-estate/$code'
      preLoaderRoute: typeof RealEstateCodeRouteImport
      parentRoute: typeof RealEstateRoute
    }
    '/products/$code': {
      id: '/products/$code'
      path: '/$code'
      fullPath: '/products/$code'
      preLoaderRoute: typeof ProductsCodeRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/livestock/$code': {
      id: '/livestock/$code'
      path: '/$code'
      fullPath: '/livestock/$code'
      preLoaderRoute: typeof LivestockCodeRouteImport
      parentRoute: typeof LivestockRoute
    }
    '/blog/guide-to-buying-agricultural-land-tamil-nadu': {
      id: '/blog/guide-to-buying-agricultural-land-tamil-nadu'
      path: '/blog/guide-to-buying-agricultural-land-tamil-nadu'
      fullPath: '/blog/guide-to-buying-agricultural-land-tamil-nadu'
      preLoaderRoute: typeof BlogGuideToBuyingAgriculturalLandTamilNaduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LivestockRouteChildren {
  LivestockCodeRoute: typeof LivestockCodeRoute
}

const LivestockRouteChildren: LivestockRouteChildren = {
  LivestockCodeRoute: LivestockCodeRoute,
}

const LivestockRouteWithChildren = LivestockRoute._addFileChildren(
  LivestockRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCodeRoute: typeof ProductsCodeRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCodeRoute: ProductsCodeRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface RealEstateRouteChildren {
  RealEstateCodeRoute: typeof RealEstateCodeRoute
}

const RealEstateRouteChildren: RealEstateRouteChildren = {
  RealEstateCodeRoute: RealEstateCodeRoute,
}

const RealEstateRouteWithChildren = RealEstateRoute._addFileChildren(
  RealEstateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LivestockRoute: LivestockRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  RealEstateRoute: RealEstateRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogGuideToBuyingAgriculturalLandTamilNaduRoute:
    BlogGuideToBuyingAgriculturalLandTamilNaduRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
